version: '3'
networks:
  luby-cash:
    external: true
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: pgdb
      POSTGRES_DB: luby_cash
    ports:
      - '5433:5432'
    networks:
      - luby-cash
  app:
    depends_on:
      - database
    build: .
    command: npm start
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app
    networks:
      - luby-cash
